<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LexisNexis.BLL\LexisNexis.BLL.csproj" />
    <ProjectReference Include="..\LexisNexis.Common\LexisNexis.Common.csproj" />
    <ProjectReference Include="..\LexisNexis.DAL\LexisNexis.DAL.csproj" />
  </ItemGroup>

</Project>
